#:schema node_modules/wrangler/config-schema.json
name = "font-decision-engine"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".vercel/output/static"

# Bindings (Prepare for future use - e.g. AI, D1, KV)
# [ai]
# binding = "AI"

# [vars]
# ENVIRONMENT = "production"
